//@version=6
indicator("MM Trap Pro Compact",overlay=true)
l=input.int(20)
m=input.float(2)
b=input.float(.5)
hv=volume>ta.sma(volume,l)*m
bp=math.abs(close-open)/open*100
bear=close>open and hv and close<high[1] and bp>b
bull=close<open and hv and close>low[1] and bp>b
plotshape(bear,style=shape.labeldown,location=location.abovebar,text="SELL")
plotshape(bull,style=shape.labelup,location=location.belowbar,text="BUY")