//@version=6
indicator("MM Trap Pro", overlay=true, max_labels_count=100)

groupCore="Core Settings", groupVis="Visual Settings", groupLegend="Legend / Dashboard"
length=input.int(20,"Volume Length",minval=1,group=groupCore)
mult=input.float(2.0,"Volume Multiplier",minval=0.1,step=0.1,group=groupCore)
minBodyPercent=input.float(0.5,"Min Body %",minval=0.0,step=0.1,group=groupCore)
showBearTrapLine=input.bool(true,"Show Bear Trap Line",group